# Generated by Django 5.0 on 2024-01-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='old_id',
        ),
    ]
