# Generated by Django 5.0 on 2024-01-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_remove_comment_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('thumbup', 'Thumbs Up'), ('thumbdown', 'Thumbs Down'), ('heart', 'Heart'), ('brokenheart', 'Broken Heart'), ('hundred', 'Hundred'), ('confused', 'Confused'), ('funny', 'Funny'), ('surprised', 'Surprised')], max_length=30),
        ),
    ]
