# Generated by Django 4.2.6 on 2023-10-30 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_alter_businessarea_unique_together'),
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='agencies.agency'),
        ),
        migrations.AlterField(
            model_name='address',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='agencies.branch'),
        ),
    ]
