# Generated by Django 4.2.6 on 2023-11-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_aec',
            field=models.BooleanField(default=False, help_text='Whether this user can act as animal ethics committee if not an admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_herbarium_curator',
            field=models.BooleanField(default=False, help_text='Whether this user can act as a herbarium curator if not an admin'),
        ),
    ]
