# Generated by Django 5.0.6 on 2024-05-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="expertise",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
