# Generated by Django 5.1 on 2024-08-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_display_first_name_user_display_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="display_first_name",
            field=models.CharField(
                help_text="Automatically populated display name with first name. This is to separate from OIM's SSO and displaying on the Annual Report with accents etc.",
                max_length=201,
                verbose_name="Display First Name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="display_last_name",
            field=models.CharField(
                help_text="Automatically populated display name with last name. This is to separate from OIM's SSO and displaying on the Annual Report with accents etc.",
                max_length=201,
                verbose_name="Display Last Name",
            ),
        ),
    ]
