# Generated by Django 5.1 on 2024-08-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_publicstaffprofile_publications_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publicstaffprofile",
            old_name="about_me",
            new_name="about",
        ),
    ]
