# Generated by Django 5.1 on 2024-08-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_educationentry_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='expertise',
        ),
    ]
