# Generated by Django 5.1 on 2024-08-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_userprofile_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicstaffprofile",
            name="it_asset_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
