# Generated by Django 5.1.1 on 2024-09-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_educationentry_qualification_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicstaffprofile',
            name='public_email',
            field=models.EmailField(blank=True, help_text='Publicly displayed email address.', max_length=254, null=True),
        ),
    ]
