# Generated by Django 5.1.5 on 2025-01-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_publicstaffprofile_public_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationentry',
            name='start_year',
        ),
    ]
