# Generated by Django 5.1.5 on 2025-02-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_educationentry_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicstaffprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
