# Generated by Django 4.2.6 on 2023-10-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchfunction',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
