# Generated by Django 5.0 on 2024-01-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.PositiveIntegerField(default=2024, help_text='The project year with four digits, e.g. 2014'),
        ),
    ]
