# Generated by Django 5.1.2 on 2024-10-28 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_projectmember_caretaker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmember",
            name="caretaker",
        ),
    ]
