# Generated by Django 5.1.5 on 2025-01-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_projectmember_caretaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.PositiveIntegerField(default=2025, help_text='The project year with four digits, e.g. 2014'),
        ),
    ]
