# Generated by Django 5.1.6 on 2025-02-07 15:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_project_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="hidden_from_staff_profiles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
