# Generated by Django 5.1.1 on 2024-09-19 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "adminoptions",
            "0003_adminoptions_guide_about_adminoptions_guide_admin_and_more",
        ),
        ("projects", "0006_alter_externalprojectdetails_aims_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "secondary_users",
                    models.JSONField(
                        blank=True,
                        help_text="An array of user pks to merge or set caretaker",
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("deleteproject", "Delete Project"),
                            ("mergeuser", "Merge User"),
                            ("setcaretaker", "Set Caretaker"),
                        ],
                        default="deleteproject",
                        max_length=50,
                    ),
                ),
                (
                    "reasoning",
                    models.TextField(
                        blank=True,
                        help_text="The requestor's reasoning for the task",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "primary_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merge_admintasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admintasks",
                        to="projects.project",
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adminrequests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Tasks",
            },
        ),
    ]
