# Generated by Django 5.1.2 on 2024-10-17 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminoptions", "0005_alter_admintask_options_admintask_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admintask",
            name="reasoning",
        ),
    ]
