# Generated by Django 5.1.2 on 2024-10-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminoptions", "0006_remove_admintask_reasoning"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admintask",
            old_name="requestor",
            new_name="requester",
        ),
    ]
