# Generated by Django 5.1.2 on 2024-10-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminoptions', '0007_rename_requestor_admintask_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintask',
            name='reason',
            field=models.TextField(blank=True, help_text="The requester's reasoning for the task", null=True),
        ),
    ]
