# Generated by Django 5.1.7 on 2025-04-03 03:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminoptions", "0010_remove_caretaker_start_date_alter_caretaker_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideSection",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                ("show_divider_after", models.BooleanField(default=False)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="adminoptions",
            name="guide_content",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores all guide content with field keys as dictionary keys",
            ),
        ),
        migrations.CreateModel(
            name="ContentField",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("field_key", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_fields",
                        to="adminoptions.guidesection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("section", "field_key")},
            },
        ),
    ]
