# Generated by Django 5.2.11 on 2026-02-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminoptions", "0011_guidesection_adminoptions_guide_content_contentfield"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Caretaker",
        ),
    ]
