# Generated by Django 4.2.5 on 2023-10-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgencyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_file", models.URLField(blank=True, null=True)),
                ("file", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Agency Image",
                "verbose_name_plural": "Agency Images",
            },
        ),
        migrations.CreateModel(
            name="AnnualReportMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_file", models.URLField(blank=True, null=True)),
                ("file", models.URLField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cover", "Cover"),
                            ("rear_cover", "Rear Cover"),
                            ("sdchart", "Service Delivery Chart"),
                            ("service_delivery", "Service Delivery"),
                            ("research", "Research"),
                            ("partnerships", "Partnerships"),
                            ("collaborations", "Collaborations"),
                            ("student_projects", "Student Projects"),
                            ("publications", "Publications"),
                            ("pdf", "PDF"),
                        ],
                        max_length=140,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annual Report Media",
                "verbose_name_plural": "Annual Report Media",
            },
        ),
        migrations.CreateModel(
            name="BusinessAreaPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_file", models.URLField(blank=True, null=True)),
                ("file", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Business Area Image",
                "verbose_name_plural": "Business Area Images",
            },
        ),
        migrations.CreateModel(
            name="ProjectDocumentPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_file", models.URLField(blank=True, null=True)),
                ("file", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Project Document PDF",
                "verbose_name_plural": "Project Document PDFs",
            },
        ),
        migrations.CreateModel(
            name="ProjectPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_file", models.URLField(blank=True, null=True)),
                ("file", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Project Image",
                "verbose_name_plural": "Project Images",
            },
        ),
        migrations.CreateModel(
            name="UserAvatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_file", models.URLField(blank=True, null=True)),
                ("file", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "User Avatar Image",
                "verbose_name_plural": "User Avatar Images",
            },
        ),
    ]
