# Generated by Django 4.2.6 on 2023-10-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyimage',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='user-uploads/'),
        ),
        migrations.AlterField(
            model_name='agencyimage',
            name='old_file',
            field=models.ImageField(blank=True, null=True, upload_to='user-uploads/'),
        ),
    ]
