# Generated by Django 5.0.6 on 2024-07-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphoto',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
