# Generated by Django 4.2.6 on 2023-10-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0004_alter_agencyimage_file_alter_agencyimage_old_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyimage',
            name='old_file',
        ),
        migrations.RemoveField(
            model_name='annualreportmedia',
            name='old_file',
        ),
        migrations.RemoveField(
            model_name='businessareaphoto',
            name='old_file',
        ),
        migrations.RemoveField(
            model_name='projectdocumentpdf',
            name='old_file',
        ),
        migrations.RemoveField(
            model_name='projectphoto',
            name='old_file',
        ),
        migrations.RemoveField(
            model_name='useravatar',
            name='old_file',
        ),
        migrations.AlterField(
            model_name='agencyimage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
