# Generated by Django 5.0.7 on 2024-07-23 06:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0004_aecendorsementpdf_size_agencyimage_size_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyAnnualReportPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="annual_reports/legacy/pdfs/"
                    ),
                ),
                ("size", models.PositiveIntegerField(default=0)),
                (
                    "year",
                    models.PositiveBigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2005),
                            django.core.validators.MaxValueValidator(2019),
                        ]
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legacy_annual_report_pdf_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Legacy Annual Report PDF",
                "verbose_name_plural": "Legacy Annual Report PDFs",
            },
        ),
    ]
