# Generated by Django 4.2.6 on 2023-10-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0006_annualreportmedia_old_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useravatar',
            name='old_file',
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='file',
            field=models.FileField(upload_to='user_avatars/'),
        ),
    ]
