# Generated by Django 4.2.6 on 2023-10-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0007_remove_useravatar_old_file_alter_useravatar_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user_avatars/'),
        ),
    ]
