# Generated by Django 4.2.6 on 2023-10-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0008_alter_useravatar_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyimage',
            name='file',
            field=models.ImageField(upload_to='agencies/'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars/'),
        ),
    ]
