# Generated by Django 4.2.6 on 2023-10-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0009_alter_agencyimage_file_alter_useravatar_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessareaphoto',
            name='old_file',
        ),
        migrations.RemoveField(
            model_name='projectphoto',
            name='old_file',
        ),
        migrations.AlterField(
            model_name='businessareaphoto',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='business_areas/'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
