apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
secretGenerator:
  - name: spms-env
    type: Opaque
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../base
  - ingress.yaml
  - media_pvc.yaml
  - pdb.yaml
labels:
  - includeSelectors: true
    pairs:
      variant: prod
patches:
  - path: deployment_patch.yaml
  - path: deployment_hpa_patch.yaml
  - path: service_patch.yaml
