apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spms-media-data
spec:
  storageClassName: azurefile-csi-retain-zrs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
