# Generated by Django 4.2.2 on 2023-08-07 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="internal_authors",
            field=models.ManyToManyField(
                related_name="publications", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="projectplan",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_plan_details",
                to="documents.projectdocument",
            ),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectdocument",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectclosure",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_closure_details",
                to="documents.projectdocument",
            ),
        ),
        migrations.AddField(
            model_name="progressreport",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_report_details",
                to="documents.projectdocument",
            ),
        ),
        migrations.AddField(
            model_name="progressreport",
            name="report",
            field=models.ForeignKey(
                blank=True,
                help_text="The annual report publishing this Report",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.annualreport",
            ),
        ),
        migrations.AddField(
            model_name="endorsement",
            name="project_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endorsements",
                to="documents.projectplan",
            ),
        ),
        migrations.AddField(
            model_name="conceptplan",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concept_plan_details",
                to="documents.projectdocument",
            ),
        ),
        migrations.AddField(
            model_name="annualreport",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="annualreport",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
