# Generated by Django 4.2.6 on 2023-11-30 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='projects.project'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='report',
            field=models.ForeignKey(blank=True, help_text='The annual report publishing this StudentReport', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.annualreport'),
        ),
    ]
