# Generated by Django 4.2.6 on 2023-11-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='year',
            field=models.PositiveIntegerField(help_text='The year on which this progress report reports on with four digits, e.g. 2014 for FY 2013/14.'),
        ),
    ]
