# Generated by Django 4.2.6 on 2023-11-10 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_progressreport_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='report',
            field=models.ForeignKey(help_text='The annual report publishing this Report', on_delete=django.db.models.deletion.CASCADE, to='documents.annualreport'),
        ),
    ]
