# Generated by Django 5.0.7 on 2024-08-02 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_conceptplan_budget_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Publication",
        ),
    ]
