# Generated by Django 4.2.6 on 2023-11-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_progressreport_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endorsement',
            name='ae_endorsement',
        ),
        migrations.RemoveField(
            model_name='endorsement',
            name='bm_endorsement',
        ),
        migrations.RemoveField(
            model_name='endorsement',
            name='data_manager_endorsement',
        ),
        migrations.RemoveField(
            model_name='endorsement',
            name='hc_endorsement',
        ),
        migrations.AddField(
            model_name='endorsement',
            name='ae_endorsement_provided',
            field=models.BooleanField(default=False, help_text="The Animal Ethics Committee's endorsement of the planned direct interaction with animals. Approval process is currently handled outside of SPMS."),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='ae_endorsement_required',
            field=models.BooleanField(default=False, help_text='Whether Animal Ethics Committee Endorsement is Required.'),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='bm_endorsement_provided',
            field=models.BooleanField(default=False, help_text="The Biometrician's endorsement of the methodology's statistical validity."),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='bm_endorsement_required',
            field=models.BooleanField(default=False, help_text='Whether Biometrician Endorsement is Required.'),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='dm_endorsement_provided',
            field=models.CharField(default=False, help_text="The Data Manager's endorsement of the project's data management.             The DM will help to set up Wiki pages, data catalogue permissions,             scientific sites, and advise on metadata creation."),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='dm_endorsement_required',
            field=models.BooleanField(default=False, help_text="Whether the data manager's endorsement is required."),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='hc_endorsement_provided',
            field=models.BooleanField(default=False, help_text="The Herbarium Curator's endorsement of the planned collection of voucher specimens."),
        ),
        migrations.AddField(
            model_name='endorsement',
            name='hc_endorsement_required',
            field=models.BooleanField(default=False, help_text='Whether Herbarium Curator Endorsement is Required.'),
        ),
    ]
