# Generated by Django 4.2.6 on 2023-11-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_endorsement_ae_endorsement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='dm_endorsement_provided',
            field=models.BooleanField(default=False, help_text="The Data Manager's endorsement of the project's data management.             The DM will help to set up Wiki pages, data catalogue permissions,             scientific sites, and advise on metadata creation."),
        ),
    ]
