# Generated by Django 4.2.6 on 2023-11-15 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectdetail_service'),
        ('documents', '0006_alter_endorsement_dm_endorsement_provided'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentreport',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='bm_endorsement_required',
            field=models.BooleanField(default=True, help_text='Whether Biometrician Endorsement is Required.'),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='dm_endorsement_required',
            field=models.BooleanField(default=True, help_text="Whether the data manager's endorsement is required."),
        ),
        migrations.AlterUniqueTogether(
            name='progressreport',
            unique_together={('report', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='studentreport',
            unique_together={('report', 'project')},
        ),
    ]
