# Generated by Django 5.2.4 on 2025-07-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_custompublication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectclosure',
            name='intended_outcome',
            field=models.CharField(blank=True, choices=[('completed', 'Completed with final update'), ('terminated', 'Terminated')], default='completed', help_text='The intended project status outcome of this closure', max_length=300, null=True),
        ),
    ]
