# Generated by Django 4.2.6 on 2023-11-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_conceptplan_project_projectclosure_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectplan',
            name='involves_animals',
        ),
        migrations.RemoveField(
            model_name='projectplan',
            name='involves_plants',
        ),
        migrations.AlterField(
            model_name='studentreport',
            name='year',
            field=models.PositiveIntegerField(help_text='The year on which this progress report reports on with four digits, e.g. 2014 for FY 2013/14.'),
        ),
    ]
