# Generated by Django 5.2.10 on 2026-02-03 02:20

from django.db import migrations, models

import documents.utils.html_tables


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_alter_projectclosure_intended_outcome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conceptplan",
            name="budget",
            field=models.TextField(
                blank=True,
                default=documents.utils.html_tables.default_concept_plan_budget,
                help_text="Indicate the operating budget for the first three years, or for a time span appropriate for the Project's life time.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="conceptplan",
            name="staff_time_allocation",
            field=models.TextField(
                blank=True,
                default=documents.utils.html_tables.default_staff_time_allocation,
                help_text="Summarise staff time allocation by role for the first three years, or for a time span appropriate for the Project's life time",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectplan",
            name="operating_budget",
            field=models.TextField(
                blank=True,
                default=documents.utils.html_tables.default_internal_budget,
                help_text="Estimated budget: consolidated DBCA funds",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectplan",
            name="operating_budget_external",
            field=models.TextField(
                blank=True,
                default=documents.utils.html_tables.default_external_budget,
                help_text="Estimated budget: external funds",
                null=True,
            ),
        ),
    ]
