# Generated by Django 4.2.6 on 2023-11-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_projectplan_involves_animals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endorsement',
            name='dm_endorsement_provided',
        ),
        migrations.RemoveField(
            model_name='endorsement',
            name='dm_endorsement_required',
        ),
    ]
