# Generated by Django 5.2.11 on 2026-02-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_use_centralized_html_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualreport',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='projectdocument',
            name='old_id',
        ),
    ]
