# Generated by Django 4.2.4 on 2023-08-31 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agencies", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="division",
            options={
                "verbose_name": "Department Division",
                "verbose_name_plural": "Department Divisions",
            },
        ),
    ]
