# Generated by Django 4.2.6 on 2023-10-30 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businessarea',
            unique_together={('name', 'agency')},
        ),
    ]
