# Generated by Django 5.0.1 on 2024-02-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessarea',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessarea',
            name='slug',
            field=models.SlugField(blank=True, help_text="A URL-sage acronym of the BA's name without whitespace", null=True),
        ),
    ]
