# Generated by Django 5.1.7 on 2025-03-17 00:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_businessarea_caretaker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='directorate_email_list',
            field=models.ManyToManyField(blank=True, help_text='Users who should receive email communications for this division', related_name='email_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
