# Generated by Django 4.2.7 on 2023-12-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('logged', 'Logged'), ('inprogress', 'In Progress'), ('fixed', 'Fixed')], default='new', max_length=20),
        ),
    ]
