# Generated by Django 5.2.11 on 2026-02-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="area",
            name="old_id",
        ),
    ]
