apiVersion: v1
kind: Service
metadata:
  name: spms-clusterip
spec:
  type: ClusterIP
  ports:
  - name: backend
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: frontend
    port: 3000
    protocol: TCP
    targetPort: 3000
