name: Docker Image CI for GHCR

on:
    push:
        tags:
            - "*"

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker
              run: docker login --username idabblewith --password ${{ secrets.GH_PAT }} ghcr.io

            - name: Get the tag name
              id: tag
              run: echo "::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}"

            - name: Build and Push Image
              run: |
                  docker build . --tag ghcr.io/dbca-wa/science-projects-service:${{ steps.tag.outputs.TAG_NAME }}
                  docker push ghcr.io/dbca-wa/science-projects-service:${{ steps.tag.outputs.TAG_NAME }}
                  docker tag ghcr.io/dbca-wa/science-projects-service:${{ steps.tag.outputs.TAG_NAME }} ghcr.io/dbca-wa/science-projects-service:latest
                  docker push ghcr.io/dbca-wa/science-projects-service:latest
