name: Docker Image CI for GHCR
'on': push
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get the version from the tag
        id: get_version
        run: echo "::set-output name=version::$(git tag -l --points-at HEAD | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' || echo 'v0.0.$((1 + $(git rev-list --count HEAD)))')"

      - name: Build and Push Image
        run: |
          docker login --username idabblewith --password ${{ secrets.GH_PAT }} ghcr.io
          docker buildx create --use
          docker buildx build . --tag ghcr.io/dbca-wa/science-projects-service:${{ steps.get_version.outputs.version }} --push

      - name: Tag the image as 'latest'
        run: |
          latest_tag="ghcr.io/dbca-wa/science-projects-service:latest"
          versioned_tag="ghcr.io/dbca-wa/science-projects-service:${{ steps.get_version.outputs.version }}"
          docker tag $versioned_tag $latest_tag
          docker push $latest_tag